version: '1'
services:
  frontend:
    container_name: front-end
    build: frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    ports:
      - 3000:3000
  server:
    container_name: server
    build: ./server
    volumes:
      - ./server/target/jar:/app
    ports:
      - 8888:8888
